"""empty message

Revision ID: 465a34241e90
Revises: 72d5107c65ce
Create Date: 2024-07-03 15:48:44.923095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465a34241e90'
down_revision = '72d5107c65ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetas')
    # ### end Alembic commands ###
