"""empty message

Revision ID: 72d5107c65ce
Revises: e30d7aaaa02a
Create Date: 2024-07-01 19:29:28.905233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d5107c65ce'
down_revision = 'e30d7aaaa02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('hair', sa.String(length=250), nullable=False),
    sa.Column('race', sa.String(length=250), nullable=False),
    sa.Column('years_old', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Characters')
    # ### end Alembic commands ###
